### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by Nonkonform** [Nonkonform/pinkdot-issues#1]
*AKTUELL*
<img width="432" alt="screenshot 2015-10-05 21 59 34" src="https://cloud.githubusercontent.com/assets/3322908/10291889/79549494-6bac-11e5-8836-31c4c571be46.png">

*SO SOLL ES SEIN*
<img width="413" alt="screenshot 2015-10-05 21 59 43" src="https://cloud.githubusercontent.com/assets/3322908/10291890/795573f0-6bac-11e5-9ef3-ed25863cbd0f.png">

border: 1px solid #9B9B9B;
border radius = 2px
background: rgba(0,0,0,0.50);
font = lato
font-weight: 300; 
font-size: 18px;
letter-spacing: 1.28px;
weiße kontur rechts muss weg

**Comment by gestaltika** [comment]
fixed
