### ISSUE TITLE
hover states

### ISSUE THREAD

**Issue by Nonkonform** [Nonkonform/pinkdot-issues#10]
@gestaltika  maybe thats easy for fixing all hover states of buttons?

**buttons and links**
@primary-color: #XXX;
@primary-color-darker: darken(@primary-color, 20%);

**social-media icons** 
@primary-color-lighter: lighten(@primary-color, 20%);

**Comment by gestaltika** [comment]
Added for links and buttons.

**Comment by gestaltika** [comment]
Added for social media icons
