### ISSUE TITLE
Input footer – page wettbewerb 

### ISSUE THREAD

**Issue by Nonkonform** [Nonkonform/pinkdot-issues#2]
**mobile**
<img width="389" alt="screenshot 2015-10-05 22 09 11" src="https://cloud.githubusercontent.com/assets/3322908/10292133/d8d16900-6bad-11e5-830b-9e0b0f6a2ecf.png">

bricht momentan so um

**other views**
<img width="460" alt="screenshot 2015-10-05 22 12 25" src="https://cloud.githubusercontent.com/assets/3322908/10292216/4aa6f07c-6bae-11e5-9776-c25466df1abe.png">

**so soll es sein**
<img width="379" alt="screenshot 2015-10-05 22 13 44" src="https://cloud.githubusercontent.com/assets/3322908/10292233/68d3cb92-6bae-11e5-9860-730a983e9665.png">

**Comment by gestaltika** [comment]
fixed
