### ISSUE TITLE
pinkdot-logo use new SVG

### ISSUE THREAD

**Issue by Nonkonform** [Nonkonform/pinkdot-issues#3]
old: 
<img width="56" alt="screenshot 2015-10-05 22 15 52" src="https://cloud.githubusercontent.com/assets/3322908/10292299/b7233ed6-6bae-11e5-8db2-2a958a66ba45.png">

new: 
<img width="50" alt="screenshot 2015-10-05 22 16 58" src="https://cloud.githubusercontent.com/assets/3322908/10292321/d51bad06-6bae-11e5-929a-f848cd43f18c.png">

@gestaltika liegt schon im dropbox ordner

**Comment by gestaltika** [comment]
changed
