### ISSUE TITLE
grid settings for tablet and desktop view

### ISSUE THREAD

**Issue by Nonkonform** [Nonkonform/pinkdot-issues#7]
hier gibt es noch einige unstimmigkeiten zum eigentlichen layout.. 

@gestaltika wir sollten einfach ein flexboxgrid mit einbinden... das würde viel zeit sparen. http://flexboxgrid.com/ gerade was so offset regeln angeht... z.B. Text: SALONE DEL M... dieser müsste links und rechts einen offset bekommen. Anbei mal ein Screenshot.

<img width="685" alt="screenshot 2015-10-06 15 16 14" src="https://cloud.githubusercontent.com/assets/3322908/10309501/3af640e4-6c3d-11e5-9360-6a6c78f398d8.png">

*Tablet Aktuell* 
<img width="763" alt="screenshot 2015-10-06 15 29 06" src="https://cloud.githubusercontent.com/assets/3322908/10310187/fa093164-6c40-11e5-9dff-562740cd744d.png">

*Vorlage*
<img width="386" alt="screenshot 2015-10-06 15 28 22" src="https://cloud.githubusercontent.com/assets/3322908/10310185/f6d4c81e-6c40-11e5-9a89-9d7e2b2823e1.png">

**Comment by gestaltika** [comment]
added and fixed most annoying stuff
